### ISSUE TITLE
Next does nothing when currentPage === 1

### ISSUE THREAD

**Issue by daviadenisco** [codenaz/react-paginator#8] opened 2020-01-06 16:39 UTC
When the current page is 1, the Next button does not work. It works on all other pages.

**Comment by codenaz** [comment] 2020-01-21 12:06
I am unable to reproduce this bug. Posting source code that shows how you are using it might be helpful.

**Comment by codenaz** [comment] 2020-01-30 06:45
Since there are no further updates on this and I am unable to reproduce this bug I will be closing this issue.

**Closed by codenaz** 2020-01-30 06:45 UTC
